### ISSUE TITLE
Event to Change areas dynamically 

### ISSUE THREAD

**Issue by ghachemsaif** [delkant/angular-areas#5]
Hello, 
Thanks for this awesome plugin, 
But i have a litle problem : 

How i can make an event to change the point instantly. 
For the moment i have tried this in my controller : 

```
$scope.ChangeAreas = function () {
            var NewtestData = [{
                "x": 557,
                "y": 135,
                "z": 500,
                "height": 75,
                "width": 75,
                "name": '',
                "cssClass": "marker_add mrk1",
                "id": 37,
                "description": "Menu"
            }];
            $scope.fields900 = NewtestData.slice(0);
            $scope.$apply();
            console.log('change')
        }
```

**Comment by delkant** [comment]
Hi Thanks, 
What do you mean by changing the points? you want to be able to move a box area passing by the coordinates? or you want to detect an event when a box area is changing?

**Comment by ghachemsaif** [comment]
actually i want to make a button to change the areas object, and add another areas

**Comment by delkant** [comment]
There is a important field miss in the documentation 'areaid' you can assign a unique areaid to every area box you are creating and then iterate through the areas to find out if that is the area you want to change, modify that area, and then $scope.$apply()

**Comment by ghachemsaif** [comment]
I get an error : 
`Error: [$rootScope:inprog] $digest already in progress`

help please !
https://jsfiddle.net/95joj0cL/2/

**Comment by delkant** [comment]
http://jsfiddle.net/a21xt52h/6/

**Comment by ghachemsaif** [comment]
Delkant, 
Thanks But the areas will duplicated after the change event 
Look at this please : http://jsfiddle.net/a21xt52h/7/
