### ISSUE TITLE
Button to add another area

### ISSUE THREAD

**Issue by ghachemsaif** [delkant/angular-areas#6]
Hello, 
i want to make a button to add an area with a specific datas : 
I tried like this : 

```
 $scope.addAnotherMarker =function () {
            var Newareas =
                {
                    "x": 957,
                    "y": 335,
                    "z": 500,
                    "height": 75,
                    "width": 75,
                    "name": "name",
                    "cssClass": 'class_red' ,
                    "id":'3',
                    "description": "Menu"
                }
            ;
            var x = angular.fromJson($scope.fields900);
            console.log(x);
            x.push(Newareas);
       
// Set my variable 
           $scope.fields900 = x;
        }
```

But it didnt refresh my areas

**Comment by delkant** [comment]
Can you try 

`$scope.$apply();` 

after modifying the area.

why? -> https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$apply

**Comment by ghachemsaif** [comment]
Yes i have tried with  $scope.$apply(), but it didnt work 
I dont get a the rendering of the new area.
I even tried with : ` $scope.$emit('ngAreas:destroy');
                $scope.$emit('ngAreas:reload');`
Here, i get the new area. 
But when i trie to change the posistion of the area, and reload my event to add another one, the first area dont keep the good new position

**Comment by delkant** [comment]
It is hard to see what you are doing with just that code you shared here.

Can you share more of what you are trying to do in https://jsfiddle.net/  or some tool like that

**Comment by ghachemsaif** [comment]
https://jsfiddle.net/95joj0cL/2/
here is it

**Comment by delkant** [comment]
You are missing so many parts on that code, actually what you put on  jsfiddle is not even running.

Please try this: http://jsfiddle.net/a21xt52h/6/
