### ISSUE TITLE
Areas being duplicated after firing the change event twice

### ISSUE THREAD

**Issue by ghachemsaif** [delkant/angular-areas#8]
Hello,
The areas are being duplicated after the change event twice
Look at this please : http://jsfiddle.net/a21xt52h/7/

--> Click the button 'change areas' twice and you will see that the areas are duplicated

**Comment by delkant** [comment]
Sorry this doesn't seem to be problem with the library. Is not a bug, you will have to check yourself to find a valid implementation.
